

# This file was *autogenerated* from the file pfs_per_graph.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)
from sage.combinat.cartesian_product import CartesianProduct_iters

def numtopf(num, n=False):
    if not n:
        k = _sage_const_1 
        while (k+_sage_const_1 )**(k-_sage_const_1 ) < num:
            k += _sage_const_1 
        n = k
    digits = [(num//((n+_sage_const_1 )**j))%(n+_sage_const_1 ) for j in range(n-_sage_const_1 )]
    digits.reverse()
    pps = [[(i+_sage_const_1 +sum(digits[_sage_const_0 :j]))%(n+_sage_const_1 ) for j in range(n)] for i in range(n)]
    for pp in pps:
        wipp = sorted(pp)
        ispf = all([wipp[i] <= i+_sage_const_1  for i in range(n)])
        if _sage_const_0  not in wipp and ispf:
            return pp
    return "ERROR"

def pf_is_friendly(pf, graph):
    n = len(pf)
    out = [_sage_const_0 ]*n
    for i in range(n):
        fail = True
        for j in range(pf[i]-_sage_const_1 , n):
            left = max(_sage_const_0 , j-_sage_const_1 )
            right = min(j+_sage_const_1 , n-_sage_const_1 )
            if out[j] == _sage_const_0  and (out[left] == _sage_const_0  or out[left] in graph[i+_sage_const_1 ]) and (out[right] == _sage_const_0  or out[right] in graph[i+_sage_const_1 ]):
                out[j] = i+_sage_const_1 
                fail = False
                break
        if fail: 
            return False
    return True

def all_pfs_for_graph(graph):
    n = graph.order()
    pfs = [numtopf(i,n) for i in range((n+_sage_const_1 )**(n-_sage_const_1 ))]
    graph_pfs = []

    for pf in pfs:
        if pf_is_friendly(pf, graph):
            graph_pfs.append(pf)
    return graph_pfs

def all_paths_for_pf(pf):
    n = len(pf)
    labelings = list(Permutations(n))
    paths = []
    for label in labelings:
        graph = Graph([(label[i], label[i+_sage_const_1 ]) for i in range(n-_sage_const_1 )])
        if pf_is_friendly(pf, graph):
            paths.append(label)
    return paths

def outcome(pf):
    n = len(pf)
    outcome = [_sage_const_0 ]*n
    for i in range(n):
        for j in range(pf[i]-_sage_const_1 , n):
            if not outcome[j]:
                outcome[j] = i+_sage_const_1 
                break
    return outcome

def friendship_outcome(pf, graph):
    pass

def displacement(pf):
    out = outcome(pf)
    tagged = sorted(list(zip(out, list(range(len(pf))))))
    return [tagged[i][_sage_const_1 ]+_sage_const_1  - pf[i] for i in range(len(pf))]

def preimage(perm):
    n = len(perm)
    options = [[] for i in range(n)]
    for i in range(n):
        for j in range(i, -_sage_const_1 , -_sage_const_1 ):
            if perm[j] <= perm[i]:
                options[perm[i]-_sage_const_1 ].append(j+_sage_const_1 )
            else:
                break
    prefs = list(cartesian_product(options))
    return prefs

def friendship_preimage(perm, graph):
    n = len(perm)
    options = [[] for i in range(n)]
    for i in range(n):
        for j in range(i, -_sage_const_1 , -_sage_const_1 ):
            if (perm[j] <= perm[i]):
                options[perm[i]-_sage_const_1 ].append(j+_sage_const_1 )
            elif (perm[j+_sage_const_1 ] <= perm[i]) and (perm[j+_sage_const_1 ] not in graph.neighbors(perm[i], closed=True)):
                options[perm[i]-_sage_const_1 ].append(j+_sage_const_1 )
            elif (j > _sage_const_0 ) and (perm[j-_sage_const_1 ] <= perm[i]) and (perm[j-_sage_const_1 ] not in graph.neighbors(perm[i], closed=True)):
                options[perm[i]-_sage_const_1 ].append(j+_sage_const_1 )
            else:
                break
    prefs = list(cartesian_product(options))
    return prefs

n = _sage_const_4 
labels = list(Permutations(n))
paths = {lbl : Graph([(lbl[i], lbl[i+_sage_const_1 ]) for i in range(n-_sage_const_1 )]) for lbl in labels}
counts = dict()
for lbl in labels:
    pfs = all_pfs_for_graph(paths[lbl])
    if not tuple(reversed(lbl)) in counts.keys():
        counts[tuple(lbl)] = pfs

for lbl in counts.keys():
    print("--".join([str(v) for v in lbl]), "->", len(counts[lbl]))
print(len(preimage([_sage_const_1 ,_sage_const_2 ,_sage_const_4 ,_sage_const_3 ])))
print(len(friendship_preimage([_sage_const_3 ,_sage_const_4 ,_sage_const_2 ,_sage_const_1 ], Graph([(_sage_const_1 ,_sage_const_2 ), (_sage_const_2 ,_sage_const_4 ), (_sage_const_4 ,_sage_const_3 )]))))
# path = Graph([(1,2),(2,4),(4,3)])
# pfs = all_pfs_for_graph(path)
# print(*pfs, sep="\n")

